### Frozen Lake

Winter is here. You and your friends were tossing around a frisbee at the park when you made a wild throw that left the frisbee out in the middle of the lake. The water is mostly frozen, but there are a few holes where the ice has melted. If you step into one of those holes, you'll fall into the freezing water. At this time, there's an international frisbee shortage, so it's absolutely imperative that you navigate across the lake and retrieve the disc. However, the ice is slippery, so you won't always move in the direction you intend. 

The surface is described using a grid like the following:

This grid is our environment where `S` is the agent’s starting point, and it’s safe. `F` represents the frozen surface and is also safe. `H` represents a hole, and if our agent steps in a hole in the middle of a frozen lake, well, that’s not good. Finally, `G` represents the goal, which is the space on the grid where the prized frisbee is located.

The agent can navigate `left`, `right`, `up`, and `down`, and the episode ends when the agent reaches the goal or falls in a hole. It receives a reward of one if it reaches the goal, and zero otherwise.

Our agent has to navigate the grid by staying on the frozen surface without falling into any holes until it reaches the frisbee. If it reaches the frisbee, it wins with a reward of plus one. If it falls in a hole, it loses and receives no points for the entire episode.

We will use the following relation to update our Q-table values:

\begin{equation*} q^{new}\left( s,a\right) =\left( 1-\alpha \right) ~\underset{\text{old value} }{\underbrace{q\left( s,a\right) }\rule[-0.05in]{0in}{0.2in} \rule[-0.05in]{0in}{0.2in}\rule[-0.1in]{0in}{0.3in}}+\alpha \overset{\text{ learned value}}{\overbrace{\left(
                                                    R_{t+1}+\gamma \max_{a^{^{\prime }}}q\left( s^{\prime },a^{\prime }\right) \right) }} \end{equation*}

In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print(state_space_size)

16


In [4]:
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1 
discount_rate = 0.99

exploration_rate = 1 # Initialize exploration rate
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = [] #'TODO: Create a list to store all rewards'

In [7]:
# Q-learning algorithm

# For each episode
for episode in range(num_episodes):
    
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    # For each time-step within the episode
    for step in range(max_steps_per_episode): 
        
        # Exploration-exploitation trade-off to decide on an action
        exploration_rate_threshold = random.uniform(0, 1)
        
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
#             print('here')
            action = env.action_space.sample()
        
        # Taking the decided upon action
        new_state, reward, done, info = env.step(action)
#         print(new_state)
        # Update Q-table for Q(s,a)
        q_table[state, action] = (1-learning_rate)*q_table[state,action]+learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))#'TODO: Implement Q learning update rule'
        
        state = new_state #'TODO: Update state with new state'                                        
                                                 
        # Add new reward        
        rewards_current_episode +=  reward #'TODO: Add the new reward to total reward of episode'
#         print(state)
        if done == True: 
            break
#             "Break the loop if env state returns done, i.e. go to next episode"                                            
                                                                                                         
    # Exploration rate decay
#     print(q_table)
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)                                                 
                                                 
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)      

In [8]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.046000000000000034
2000 :  0.22600000000000017
3000 :  0.43200000000000033
4000 :  0.5390000000000004
5000 :  0.6330000000000005
6000 :  0.6190000000000004
7000 :  0.6930000000000005
8000 :  0.6830000000000005
9000 :  0.7060000000000005
10000 :  0.6420000000000005


In [9]:
max([1,2,3,5,1,231])

231

In [10]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.48928019 0.44784481 0.48234478 0.46183313]
 [0.29355482 0.29501351 0.29555927 0.38356953]
 [0.29766191 0.26244491 0.25960893 0.27694597]
 [0.15319479 0.07035944 0.03682483 0.06856761]
 [0.49818088 0.36306406 0.31058786 0.37275997]
 [0.         0.         0.         0.        ]
 [0.14425121 0.12756739 0.23511083 0.08106266]
 [0.         0.         0.         0.        ]
 [0.34655991 0.46704823 0.48335838 0.51978774]
 [0.40317839 0.55389818 0.47979116 0.3473756 ]
 [0.3357649  0.37076534 0.3300654  0.27428472]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3966311  0.55330765 0.67616588 0.38466144]
 [0.740201   0.86127977 0.73522636 0.7211604 ]
 [0.         0.         0.         0.        ]]


### Watch our agent play Frozen Lake by playing the best action from each state according to Q-table

In [11]:
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.7)
        
        # Choose action with highest Q-value for current state       
        action = np.argmax(q_table[state,:])
        
        # Take new action
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break

        state = new_state
               
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
